import { Role } from "../models/role";
import { User } from "../models/user";

const dummyData: User[] = [
    {
        id: '1',
        email: 'dummy@dummy.com',
        username: 'dummy',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '2',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '3',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '4',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '5',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '6',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '7',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '8',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '9',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '10',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '11',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '10',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    },
    {
        id: '11',
        email: 'test@gmail.com',
        username: 'test',
        role: Role.USER,
        dateCreate: '2021-08-01',
        dateUpdate: '2021-08-01',
        lastLogin: '2021-08-01',
        loginAttempt: 0,
        isDeleted: false,
    }
];

export default dummyData;